name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Create Package
        uses: QartemisT/packager@master
        if: ${{ github.event_name != 'pull_request' }}
        with:
          args: -g classic -n "SpellReplay-{project-version}{classic}"
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
